development:
  clients:
    default:
      database: notes_manager_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: notes_manager_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: notes_manager_production
      hosts:
        - localhost:27017