name: Notes Manager Github CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: notes_manager_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s

      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'" --health-interval=10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Verify MySQL connection
        run: |
          sudo apt-get install -y mysql-client libmysqlclient-dev
          mysql --host=127.0.0.1 --port=3306 -u root -proot -e "SHOW DATABASES;"
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host=127.0.0.1 --port=3306 -u root -proot mysql

      - name: Setup MySQL database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Verify MongoDB connection
        run: |
          mongo --eval "db.runCommand({ ping: 1 })"

      - name: Run tests
        run: bundle exec rspec